name: pft

services:
  backend:
    build:
      context: ../..
      dockerfile: Containerfile
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=pocket-finance-db.postgres.database.azure.com;Port=5432;Database=postgres;Username=pocketFinance;Password=@Chandudp2211;SSL Mode=Require;Trust Server Certificate=true
      Jwt__Issuer: pft
      Jwt__Audience: pft
      Jwt__SigningKey: CHANGE_ME_DEV_ONLY_CHANGE_ME_DEV_ONLY_32+CHARS
      Jwt__AccessTokenMinutes: "120"
      Jwt__RefreshTokenDays: "30"
    ports:
      - "8080:8080"
    networks:
      pftnet:
        aliases: ["backend"]

  frontend:
    build:
      context: ../../../pft-frontend
      dockerfile: Containerfile
      args:
        VITE_API_BASE_URL: ""
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - pftnet

networks:
  pftnet:
